# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_trans')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_trans')
    _trans = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_trans', [dirname(__file__)])
        except ImportError:
            import _trans
            return _trans
        if fp is not None:
            try:
                _mod = imp.load_module('_trans', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _trans = swig_import_helper()
    del swig_import_helper
else:
    import _trans
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

PRIuPTR = _trans.PRIuPTR
PRIdPTR = _trans.PRIdPTR
LLU = _trans.LLU
LLO = _trans.LLO
LLX = _trans.LLX
false = _trans.false
true = _trans.true
OUTCOME_GENERIC_ERROR = _trans.OUTCOME_GENERIC_ERROR
OUTCOME_PARSER_ERROR = _trans.OUTCOME_PARSER_ERROR
OUTCOME_SYNTAX_ERROR = _trans.OUTCOME_SYNTAX_ERROR
OUTCOME_FILE_ERROR = _trans.OUTCOME_FILE_ERROR
OUTCOME_SUCCESS_REQUIRED_HELP = _trans.OUTCOME_SUCCESS_REQUIRED_HELP
OUTCOME_SUCCESS = _trans.OUTCOME_SUCCESS
TRANS_TYPE_INVALID = _trans.TRANS_TYPE_INVALID
TRANS_TYPE_MONOLITHIC = _trans.TRANS_TYPE_MONOLITHIC
TRANS_TYPE_THRESHOLD = _trans.TRANS_TYPE_THRESHOLD
TRANS_TYPE_IWLS95 = _trans.TRANS_TYPE_IWLS95

def TransType_from_string(name: 'char const *') -> "TransType":
    """TransType_from_string(char const * name) -> TransType"""
    return _trans.TransType_from_string(name)

def TransType_to_string(arg1: 'TransType const') -> "char const *":
    """TransType_to_string(TransType const arg1) -> char const *"""
    return _trans.TransType_to_string(arg1)
# This file is compatible with both classic and new-style classes.


