# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_be')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_be')
    _be = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_be', [dirname(__file__)])
        except ImportError:
            import _be
            return _be
        if fp is not None:
            try:
                _mod = imp.load_module('_be', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _be = swig_import_helper()
    del swig_import_helper
else:
    import _be
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

PRIuPTR = _be.PRIuPTR
PRIdPTR = _be.PRIdPTR
LLU = _be.LLU
LLO = _be.LLO
LLX = _be.LLX
false = _be.false
true = _be.true
OUTCOME_GENERIC_ERROR = _be.OUTCOME_GENERIC_ERROR
OUTCOME_PARSER_ERROR = _be.OUTCOME_PARSER_ERROR
OUTCOME_SYNTAX_ERROR = _be.OUTCOME_SYNTAX_ERROR
OUTCOME_FILE_ERROR = _be.OUTCOME_FILE_ERROR
OUTCOME_SUCCESS_REQUIRED_HELP = _be.OUTCOME_SUCCESS_REQUIRED_HELP
OUTCOME_SUCCESS = _be.OUTCOME_SUCCESS

def BeFsm_create(be_enc: 'BeEnc_ptr', init: 'be_ptr const', invar: 'be_ptr const', trans: 'be_ptr const', list_of_be_fairness: 'node_ptr const') -> "BeFsm_ptr":
    """BeFsm_create(BeEnc_ptr be_enc, be_ptr const init, be_ptr const invar, be_ptr const trans, node_ptr const list_of_be_fairness) -> BeFsm_ptr"""
    return _be.BeFsm_create(be_enc, init, invar, trans, list_of_be_fairness)

def BeFsm_create_from_sexp_fsm(be_enc: 'BeEnc_ptr', bfsm: 'BoolSexpFsm_ptr const') -> "BeFsm_ptr":
    """BeFsm_create_from_sexp_fsm(BeEnc_ptr be_enc, BoolSexpFsm_ptr const bfsm) -> BeFsm_ptr"""
    return _be.BeFsm_create_from_sexp_fsm(be_enc, bfsm)

def BeFsm_destroy(arg1: 'BeFsm_ptr') -> "void":
    """BeFsm_destroy(BeFsm_ptr arg1)"""
    return _be.BeFsm_destroy(arg1)

def BeFsm_copy(arg1: 'BeFsm_ptr') -> "BeFsm_ptr":
    """BeFsm_copy(BeFsm_ptr arg1) -> BeFsm_ptr"""
    return _be.BeFsm_copy(arg1)

def BeFsm_get_be_encoding(arg1: 'BeFsm_ptr const') -> "BeEnc_ptr":
    """BeFsm_get_be_encoding(BeFsm_ptr const arg1) -> BeEnc_ptr"""
    return _be.BeFsm_get_be_encoding(arg1)

def BeFsm_get_init(arg1: 'BeFsm_ptr const') -> "be_ptr":
    """BeFsm_get_init(BeFsm_ptr const arg1) -> be_ptr"""
    return _be.BeFsm_get_init(arg1)

def BeFsm_get_invar(arg1: 'BeFsm_ptr const') -> "be_ptr":
    """BeFsm_get_invar(BeFsm_ptr const arg1) -> be_ptr"""
    return _be.BeFsm_get_invar(arg1)

def BeFsm_get_trans(arg1: 'BeFsm_ptr const') -> "be_ptr":
    """BeFsm_get_trans(BeFsm_ptr const arg1) -> be_ptr"""
    return _be.BeFsm_get_trans(arg1)

def BeFsm_get_fairness_list(arg1: 'BeFsm_ptr const') -> "node_ptr":
    """BeFsm_get_fairness_list(BeFsm_ptr const arg1) -> node_ptr"""
    return _be.BeFsm_get_fairness_list(arg1)

def BeFsm_apply_synchronous_product(arg1: 'BeFsm_ptr', other: 'BeFsm_ptr const') -> "void":
    """BeFsm_apply_synchronous_product(BeFsm_ptr arg1, BeFsm_ptr const other)"""
    return _be.BeFsm_apply_synchronous_product(arg1, other)

def node_ptr_to_be_ptr(node: 'node_ptr') -> "be_ptr":
    """node_ptr_to_be_ptr(node_ptr node) -> be_ptr"""
    return _be.node_ptr_to_be_ptr(node)
# This file is compatible with both classic and new-style classes.


