# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ltl2smv')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ltl2smv')
    _ltl2smv = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ltl2smv', [dirname(__file__)])
        except ImportError:
            import _ltl2smv
            return _ltl2smv
        if fp is not None:
            try:
                _mod = imp.load_module('_ltl2smv', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ltl2smv = swig_import_helper()
    del swig_import_helper
else:
    import _ltl2smv
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

PRIuPTR = _ltl2smv.PRIuPTR
PRIdPTR = _ltl2smv.PRIdPTR
LLU = _ltl2smv.LLU
LLO = _ltl2smv.LLO
LLX = _ltl2smv.LLX
false = _ltl2smv.false
true = _ltl2smv.true
OUTCOME_GENERIC_ERROR = _ltl2smv.OUTCOME_GENERIC_ERROR
OUTCOME_PARSER_ERROR = _ltl2smv.OUTCOME_PARSER_ERROR
OUTCOME_SYNTAX_ERROR = _ltl2smv.OUTCOME_SYNTAX_ERROR
OUTCOME_FILE_ERROR = _ltl2smv.OUTCOME_FILE_ERROR
OUTCOME_SUCCESS_REQUIRED_HELP = _ltl2smv.OUTCOME_SUCCESS_REQUIRED_HELP
OUTCOME_SUCCESS = _ltl2smv.OUTCOME_SUCCESS
LTL_MODULE_BASE_NAME = _ltl2smv.LTL_MODULE_BASE_NAME

def ltl2smv(uniqueId: 'unsigned int', in_ltl_expr: 'node_ptr') -> "node_ptr":
    """ltl2smv(unsigned int uniqueId, node_ptr in_ltl_expr) -> node_ptr"""
    return _ltl2smv.ltl2smv(uniqueId, in_ltl_expr)
# This file is compatible with both classic and new-style classes.


